### ISSUE TITLE
License type mismatch 

### ISSUE THREAD

**Issue by ummahusla** [npruehs/tome-editor#104]
At the top of the repository title, it says `MIT license`.

![](http://image.prntscr.com/image/19fabff25b4c447fa7fde94749daca22.png)

In the very end of the `readme.md` we can see that different license is mentioned.

`Tome is released under the GNU Lesser General Public License 3.0.`

**Comment by npruehs** [comment]
@ummahusla LGPL is correct. I honestly don't know where GitHub takes the "MIT" from - LICENSE file is LGPL. Will address that soon.

**Comment by npruehs** [comment]
Fixed by contacting GitHub support.
