### ISSUE TITLE
Reparenting broken in current build (0.8)

### ISSUE THREAD

**Issue by pgrimsehl** [npruehs/tome-editor#108]
Reparenting is completely broken when renaming a parent record in the current version (0.8):

1. Subrecords are reparented to the new record, and after that, reparented to .
Sample output when renaming Factory to Factory0:
Reparenting record ToysFactory to Factory0. 
Reparenting record ToysFactory to .
2. All child records are root records afterwards
3. All child records are duplicated in recordtreeview
4. Depending on loaded project structure, Tome crashes when attempting to rename a parent with child nodes. Call stack:

1   RaiseException                                  KERNELBASE                     0x7fffebac7788 
2   CxxThrowException                               VCRUNTIME140D                  0x7fffd8cd7b60 
3   Tome::RecordsController::getRecordById          recordscontroller.cpp     622  0x7ff6b8827606 
4   Tome::RecordsController::getAncestors           recordscontroller.cpp     124  0x7ff6b88254bc 
5   Tome::RecordTreeWidget::updateRecordItem        recordtreewidget.cpp      133  0x7ff6b883e271 
6   Tome::RecordTreeWidget::setRecords              recordtreewidget.cpp      198  0x7ff6b883d969 
7   MainWindow::refreshRecordTree                   mainwindow.cpp            1432 0x7ff6b87c6ddf 
8   MainWindow::onRecordReparented                  mainwindow.cpp            1364 0x7ff6b87c5cf4 
9   MainWindow::qt_static_metacall                  moc_mainwindow.cpp        333  0x7ff6b88894e4 
10  QMetaObject::activate                           qobject.cpp               3742 0x51dddaf2     
11  QMetaObject::activate                           qobject.cpp               3603 0x51ddd268     
12  Tome::RecordsController::recordReparented       moc_recordscontroller.cpp 263  0x7ff6b888ea4b 
13  Tome::RecordsController::reparentRecord         recordscontroller.cpp     452  0x7ff6b8826a96 
14  Tome::RecordsController::updateRecordReferences recordscontroller.cpp     868  0x7ff6b8828625 
15  Tome::RecordsController::updateRecord           recordscontroller.cpp     472  0x7ff6b8826ba4 
16  Tome::UpdateRecordCommand::redo                 updaterecordcommand.cpp   58   0x7ff6b887e34d 
17  QUndoStack::push                                qundostack.cpp            587  0x52c50869     
18  Tome::UndoController::doCommand                 undocontroller.cpp        32   0x7ff6b8875e72 
19  MainWindow::on_actionEdit_Record_triggered      mainwindow.cpp            708  0x7ff6b87c4022 
20  MainWindow::treeWidgetDoubleClicked             mainwindow.cpp            1179 0x7ff6b87c6828 

An access is attempted to a record with the new name, but the old record has not been updated yet ( see call sequence in RecordsController::updateRecord():

```
void RecordsController::updateRecord(const QString oldId, const QString newId, const QString newDisplayName, const QStringList& fieldIds, const QString& recordSetName)
{
    // Update references to record.
    this->updateRecordReferences(oldId, newId); // <-- access to a record with newId here

    // Update record itself.
    Record& record = *this->getRecordById(oldId);
    const QString oldDisplayName = record.displayName;

    bool needsSorting = oldDisplayName != newDisplayName;

    record.id = newId; // <-- updating to newId here
    record.displayName = newDisplayName;
```

Changing the call order ( update old record first, then updating references) will not work, since access to the old record is needed.

**Comment by npruehs** [comment]
Thanks for the detailed description!
