### ISSUE TITLE
Feature: Context menu / Create new record

### ISSUE THREAD

**Issue by pgrimsehl** [npruehs/tome-editor#110]
It would be handy if I could create a new record by using the right-click context menu:
1. If a record is selected, the new record is inserted as child of the selected record
2. If no record is selected, , the new record is inserted as root record

Implementing 2. would require to be abel to "unselect" the currently selected record, which is not possible atm. This action could be performed by pressing ESC and should be inserted into the undo stack.

**Comment by npruehs** [comment]
Added in commit 580a0f3dbf64c6dbafea717303fee20367042b33.
