### ISSUE TITLE
CSV import delimiter

### ISSUE THREAD

**Issue by nkoufou** [npruehs/tome-editor#125]
CSV import does not work, as it tries to split strings using ';' instead of ','

Specifically:

QStringList headers = line.split(';'); (line 47)
and 
QStringList row = line.split(';'); (line 78)

in csvrecorddatasource.cpp

**Comment by npruehs** [comment]
You are right. Most games will use commas in their texts, especially when writing tooltips or names. You should be able to export your CSV with a different delimiter. However, I can see that providing a configuration option for specifying the delimiter for the import could be a feature in the future.

**Comment by nkoufou** [comment]
Having the option to specify a delimiter would be nice, maybe something like this:

<Parameter Key="Delimiter" Value=","/>

Regarding the handling of commas in a CSV doc. Google sheets will wrap any cells in double quotes when exporting as an example. The import process will then need to leave quoted strings as is.

**Comment by npruehs** [comment]
Added in commit c1a35ff0d0cfcbc571a9f741be51d1abd37a7e2e and d40b295cc5d3f4cb46633d534c35f564e4b8b507.
