### ISSUE TITLE
Custom data types are lacking.

### ISSUE THREAD

**Issue by asusralis** [npruehs/tome-editor#128]
I need to be able to define a "format" of a custom data type so I can use them as a field.

Example: I'm creating a branching story game in the format of cards. I have a Card type which holds an array of type CardChoice. The problem is that you can't "define" a type in Tome - you're limited to primitive types, references, or enumerables. This means a field is unable to hold an actual data object.

...Unless you use references. Which I really do not want to do. I use my own ID system in that actual game I'm creating - I don't want to have to keep track of the ID's created by Tome. In fact, I completely removed everything but $RECORD_FIELDS$ when exporting so I can parse the JSON like any other normal JSON file.

References also don't work for me because each CardChoice is unique; I definitely don't want to have them separate from the actual card they're on. I got excited when I read "derived types," but they're more like constraints (which is poorly named in my opinion). 

I really am grateful you're doing this on your off-time, but I sadly cannot use this software because of the limitations above. I hope you take my post in consideration, and thanks again!

**Comment by npruehs** [comment]
Hey @asusralis!

I'm not 100% sure I understand your requirement. Would you mind providing an example JSON you're trying to achieve?

**Comment by asusralis** [comment]
Hey, thanks for the reply.

Here is a stripped down piece of my json:

```json
// Card.
  {
    "Name": "",
    "Description": "",
    "Id": 1,
    // CardChoice
    "Choices": [
      {
        "Name": "",
        "Description": "",
        "Cost": {},
        "Result": {}
      },
      {
        "Name": "",
        "Description": "",
        "Cost": {},
        "Result": {}
      }
    ]
  }
```

In this example I would need a field to be an array of custom objects (CardChoice). Because you can't define object types, it isn't possible do edit the above json in Tome without using references which I've talked about why I don't want to use them.

I need a way to create a "custom type" which contains fields. Going off of that, "Cost" and "Result" are also separate object types that I would also need to define.

**Comment by pgrimsehl** [comment]
This is indeed an interesting use case. Such a custom type could be kind of a "record template", similar to a record, but with no instantiation. Such instantiation would take place in fields of concrete records that have that record template as underlying type (single value fields, lists or maps). I like that idea :)

The closest thing you can try for the "Choices" field in the current version of Tome would be a list of maps, but even this will not work:

1. Maps can only map to one value type, so no mixture of different value types
2. List of maps are currently not working. Although I can add new map items to the list, these items are not displayed in the list edit box properly (clickable, but empty lines) and are stored as empty list items in the .tdata file.

**Comment by npruehs** [comment]
Hey @asusralis!

I understand your requirements now. Unfortunately, I can confirm that this won't see its way into Tome any time soon.

Introducing custom data types adds a whole additional layer of complexity on all levels: How should the UI look like? How should export templates be structured to allow this? What about import templates? Can these custom data types derived from again? We need to handle lists and maps of custom data as well. What types of new integrity checks do we need? How would the search experience look like for a user?

I see the requirement on your side, and I've seen it a few times before in other projects. Those projects all went down the road you've already suggested yourself: Add additional records and use references instead. This allows for more "data normalization" as well, as data can be re-used, and is similar to the approach in databases in general.

You can do that as well, and transform the data to your desired sub-objects after parsing the file. If that's not an option, I'm afraid you'll have to use a different tool until we're opening up on this again.

Thanks for your time and bringing this up!
