### ISSUE TITLE
Project settings

### ISSUE THREAD

**Issue by npruehs** [npruehs/tome-editor#16]
User should be able to edit the settings of the current project, specifying a name and description, and adding and removing data files.

**Comment by npruehs** [comment]
Use a tree view to visualize current project files.

**Comment by npruehs** [comment]
* locale
* decimals

**Comment by pgrimsehl** [comment]
The user should be able to manage all files associated with the project using this dialog

- type definition files
- field definition files
- component definition files
- recordset files

When inc;uding multiple files of the same content type in the project ( e.g. field definitions ) it must be ensured that no duplicate ids are present.

**Comment by npruehs** [comment]
Added in commit d711f2ae4023bcfa12dd1a1cb19dc9cc31a21053.
