### ISSUE TITLE
Field Facets

### ISSUE THREAD

**Issue by npruehs** [npruehs/tome-editor#46]
When adding or editing a field definition, the user can specify constraints for the field values. Values are validated against these constraints.

**Comment by npruehs** [comment]
Number: Min, Max
String: MaxLength
Reference: Base type

**Comment by pgrimsehl** [comment]
> Reference: Base type

What do you mean by Base type? Afaik records do not have a type.

If the creator of a project adheres to naming conventions for records, a filter constraint could be used to limit the possible records. For example the filter
"+SpellTrigger"
would list all records with a name containing the substring "SpellTrigger", whereas the filter
"-Debug"
will exclude all records containing the substring "Debug". Both could be combined such as in
"+NPC+Critter+PC-Location-Town"
will allow all records containing NPC or Critter or PC but not Location and not Town.

Of course there could be a new managed type in Tome, the "Record Type" (a user defined list of names as with components), which is mandatory to declare for each created record. Are there plans to implement record types in Tome?

**Comment by npruehs** [comment]
Sorry for the confusing wording: I should have written _parent record_ instead of base type. The idea behind this was exactly your suggested usage scenario: Restricting references to records with specific components - which would automatically be enforced by specifying a required parent.

As for your other suggestion, I can imagine that as well. I think I'd rather call it _omponent group_ instead of record type in that case.

Filtering by string is definitely also a valid idea!

**Comment by npruehs** [comment]
I'm curious: How badly do you need this? Is this something we should add to the next release?

**Comment by npruehs** [comment]
Added in commit be385a59508c4930b6e06a772d1fbb4dca1fe93e.
