### ISSUE TITLE
Update of records after changing a field's component property

### ISSUE THREAD

**Issue by pgrimsehl** [npruehs/tome-editor#65]
After changing a field's component property, all records using this field must be updated to reflect these changes. 
If a project is loaded the same checks must be performed.
The user must be informed about the changes that will be performed and must be able to abort the process.
Current state: changes are not reflected in records, record field/component assignment is broken in recordwindow.

**Comment by npruehs** [comment]
Well, that's odd. In my mind, records don't have any notion of components. They just store field values, and the respective components holding these fields are never used except when applying export templates. I seem to be mistaken though, will take a look at it.

**Comment by pgrimsehl** [comment]
No you're right, records do not have a direct link to components, but they always gain/lose all fields associated with a component upon selecting a component ( or a field that has a compoinent ) in the record window. Here is an example:
If a field "F1" has it's component property set to "C1" and is selected in the record window, all fields associated with "C1" are marked for that record. If we now change the component property of "F1" to "C2" and there are other fields associated with "C2", any record using "F1" must adopt all fields associated with "C2" as if "F1" was selected manually in the record window.

Hope this helps to clarify the issue.

**Comment by npruehs** [comment]
Actually, I'm afraid it's not that simple... There are multiple cases we need to consider here:

Changing the component of F1 to C2 may (or may not)

* Automatically add F1 to all records that already have all other C2 fields (in the actual data).
* Automatically remove F1 from all records that have all other C1 fields (in the actual data).
* Show the C2 checkbox as checked, and add all other C2 fields to records with F1 (in the record window).
* Not show the C2 checkbox as checked, because other C2 fields are missing, but show F1 checkbox as checked for records with F1 (in the record window).

This becomes even more complicated considering that records may (or may not) inherit any or all of the component fields.

I feel like changing the actual data is the cleanest way of handling this case, and will automatically solve all issues in the record window and with inherited fields. What do you think?

**Comment by pgrimsehl** [comment]
> I feel like changing the actual data is the cleanest way of handling this case, and will automatically solve all issues in the record window and with inherited fields.

Not sure what you mean by changing the actual data. What I'd like to see is a integrity check, that fixes these relations, either automatically on project load or triggered manually.

> 
- Automatically add F1 to all records that already have all other C2 fields (in the actual data).
- Automatically remove F1 from all records that have all other C1 fields (in the actual data).
- Show the C2 checkbox as checked, and add all other C2 fields to records with F1 (in the record window).
- Not show the C2 checkbox as checked, because other C2 fields are missing, but show F1 checkbox as checked for records with F1 (in the record window).

> This becomes even more complicated considering that records may (or may not) inherit any or all of the component fields.

Afaik it is impossible for a record to adopt only a subset of fields associated with a component in the current version of Tome. On checking/unchecking a field, ALL fields that have the same component are selected/unselected. They cannot be selected indivdually. And that is exactly the behaviour that makes me using components in the first place.

**Comment by npruehs** [comment]
> Afaik it is impossible for a record to adopt only a subset of fields associated with a component in the current version of Tome.

That's right. Except for when you change the component of a field.

> Not sure what you mean by changing the actual data. What I'd like to see is a integrity check, that fixes these relations, either automatically on project load or triggered manually.

Okay, so yes: You want the relations to be fixed immediately, for all records - and not just the next time we open the Record window? How do you want it to be fixed? There are several options, as stated above.

**Comment by pgrimsehl** [comment]
Ok, I guess we have a different view of the concept of components. Judging from the the choices you gave to handle the component change of F1 it seems that it is a valid option for you to have records that do not adopt all fields of a component. From my perspective, this state is broken. As stated in the wiki
> For Tome, components don't have any more impact right now.

but as opposed to this components are a fundamental concept for me to build my data structures. Actually, fo me, all of these steps have to be performed 
>
- Automatically add F1 to all records that already have all other C2 fields (in the actual data).
- Automatically remove F1 from all records that have all other C1 fields (in the actual data).
- Show the C2 checkbox as checked, and add all other C2 fields to records with F1 (in the record window).

whilst the last

>
- Not show the C2 checkbox as checked, because other C2 fields are missing, but show F1 checkbox as checked for records with F1 (in the record window).

means a corrupted data state to me.

Beside that, I don't think that fixing data "on access" when opening the record window is a proper way to apply such a change. If you just change the fields, save the project and export the data, no record will notice this change - unless all records are opened manually.

**Comment by npruehs** [comment]
Yes, I agree! That's what I meant above when suggesting:

> I feel like changing the actual data is the cleanest way of handling this case, and will automatically solve all issues in the record window and with inherited fields. What do you think?

I'm glad we can agree on the same view here. I will add this next.
