### ISSUE TITLE
Export templates combined in one file

### ISSUE THREAD

**Issue by pgrimsehl** [npruehs/tome-editor#66]
I definitely think there is a good reason to have a separate file for each export tag, but exactly why? I could imagine somthing like:

```
<?xml version="1.0" encoding="UTF-8"?>
<Template>
    <ExportF><!CDATA[$RECORDS$]]></ExportF>
    <ExportR><!CDATA[[$RECORD_ID$]
$RECORD_FIELDS$]]></ExportR>
    <ExportV><!CDATA[$FIELD_ID$ = $FIELD_VALUE$]]></ExportV>
    ...
</Template>
```

as export template file. Are there any issues using this approach that I'm not aware of?
If readability is a concern: when using this format I won't let the user create/edit this file manually but rather add an Export Template window to Tome that where the user can edit each string in a separate edit box, so he never gets in touch with the created output file.

**Comment by npruehs** [comment]
Readability was the main concern indeed here, as mentioned in the wiki: https://github.com/npruehs/tome-editor/wiki/Exporting-Data#crating-export-templates

Also, we prefer splitting things as much as possible, in order to improve collaboration and facilitate source control management.
