### ISSUE TITLE
Exporting subset of records

### ISSUE THREAD

**Issue by pgrimsehl** [npruehs/tome-editor#71]
The user should be able to select individual records for exporting as well as the export template used during this process.

Motivation: I'd like to manage all data in one project, but want to be able to export subsets of records in different formats. Some of them may be used directly by the game engine, others will be used as input / configuration for other tools in the content production chain.

Currrent state; Each export format requires a separate project.

**Comment by npruehs** [comment]
I think I understand where you're headed at, but to avoid any misunderstands, can you provide a minimum example of your use case? Either as project file or as simple screenschot? Do you want to export multiple roots with different export templates?

**Comment by pgrimsehl** [comment]
**Sample use case**
Image a Tome project for a game where records of type "Creature" are defined. All data ( e.g. health, faction, spells etc. ) associated with a creature is managed in Tome along with other definitions / records for other types of objects used in the game. The whole project is exported using an export template suitable for the game engine.
Now you want level designers to create maps, where instances of those creatures are placed. The map creation is done with another tool, for example [Tiled](https://github.com/bjorn/tiled). All creature definitions should be available as object types for Tiled, so the level designer can reference them correct;ly and the resulting Tiled map contains valid references to existing record definitions. To achieve this, only the "Creature" records can be selected for export and an appropriate export template is used, that will allow importing this data in Tiled.

**Implementation**
I can envision two impementations of this feature.

_Export Dialog Window_
All exporting is done using a new Export Dialog Window. In this export dialog, two main modes are available:
a) "Export all" - exports all records in the project. The user can select different options for this export, including export template, record export options ( Roots, Inner Nodes, Leafs ) and output file.
b) "Selected" - exports all selected records. The record tree view is replicated in the export dialog, adding a checkbock to each record. Checking / unchecking a parent record will check / uncheck all children. The user can select the export template used for this export as well as the and output file. The user should still be able to set some additional options ( Roots, Inner Nodes, Leafs ), so a parent can be checked to check all children, but is not necessarily exported itself

_Record context menu_
A cascading context menu is opened when right clicking on a record, showing 3 entries
a) Export with children >
b) Export children only >
c) Export record only >
The next menu level contains the available export templates ( as the Export entry in the menu bar )

The first implementation is more elaborated an opens more options to be inegrated in the export process later, as well as a place to change the current export parameters, whereas the second implementation can be integrated more easily in the existing editor.

**Comment by npruehs** [comment]
Alright, will take a look at it. Until then, should be able to work-around that by splitting up your records in multiple files (which might be a good idea, anyway) and creating two project files:

- Project A references all record files and has an export template for exporting them all for the game engine.
- Project B references just the Creatures records file and has the export template for Tiled.

**Comment by pgrimsehl** [comment]
Yes that's what I'm doing right now :)

**Comment by npruehs** [comment]
Added in commit 7bb17c22aceaed5f06f75f16ae2e67ac17633f00.
