### ISSUE TITLE
Explicit reference to field values in export templates

### ISSUE THREAD

**Issue by pgrimsehl** [npruehs/tome-editor#72]
The current export system featured by Tome using multiple export templates is very flexible and highly customizable to fit nearly any kind of output format.

However some formats are not supported. If you have an XML based output format and need to export a field value as an attribute of an XML element, this cannot be done right now, since fields are always exported as block for each record.

Consider the following record:
```
<Record Id="Unit" DisplayName="Unit">
  <Color Value="#ffffff"/>
  <Health Value="1000"/>
  <Mana Value="4000"/>
</Record>
```

that should be exported as

```
<objecttype name="Unit" color="#ffffff">
  <property name="Health" type="string" value="1000"/>
  <property name="Mana" type="string" value="4000"/>
</objecttype>
```

There is currently no way to write the value of Color within the opening object tag. The export template string for the record is limited to

```
<object type="$RECORD_ID$">
$RECORD_FIELDS$
</object>
```

which will produce

```
<object type="Unit">
  <property name="Color" value="#ffffff"/>
  <property name="Health" value="1000"/>
  <property name="Mana" value="4000"/>
</object>
```

This could be solved by introducing special notations for the $FIELD_VALUE$ and $RECORD_FIELDS$ placeholders:

The placeholder notation `$FIELD_VALUE:FieldName$` will insert the value of the field _FieldName_ in the output stream when it is encountered.
The placeholder notation `$RECORD_FIELDS!FieldName1!FieldName2!FieldNameN$` will apply the field value template for each record field **excluding** _FieldName1, FieldName2, ... FieldNameN_

The above record export template will become 

```
<object type="$RECORD_ID$" color="$FIELD_VALUE:Color$">
$RECORD_FIELDS!Color$
</object>
```

resulting in the desired output format. What do you think about this?

**Comment by npruehs** [comment]
Wow, you really found a gap here - I wasn't aware of that. I like the idea. I'm curious: How badly do you need this? Is this something we should add to the next release?

**Comment by pgrimsehl** [comment]
Currently I'm exporting data for Tiled ( which has the mentioned output format ) so it would be great to have it in the next release.

Additionally field names must not be allowed to include the character $, to allow for proper detection of the closing $ of the paceholders.

**Comment by npruehs** [comment]
Yes, you're right. I'm not 100% sure about the exact formatting, but I'll add to the milestone. Thanks for the input!

**Comment by npruehs** [comment]
Added in commit 11833c65dbb4100eecbfeb7bf2b4a21cb749f0d3.

**Comment by npruehs** [comment]
You can now explicitly write specific field values to the output stream, just as you suggested. `$FIELD_VALUE:Health$` will be replaced by the value of the Health field, for instance.

Tome will automatically omit these fields in `$RECORD_FIELDS$` placeholders.

Also, the export template file format now supports ignored records and fields in general, just in case you need them. Just open your project and save it again, that will convert it to the new format. Then, add the ids of the records or fields you want to ignore to the ignore lists:

```
    <IgnoredRecords>
        <Id>Knight</Id>
    </IgnoredRecords>
    <IgnoredFields>
        <Id>Mana</Id>
    </IgnoredFields>
```

@pgrimsehl, does this fit your needs?

**Comment by npruehs** [comment]
@pgrimsehl Would that maybe also already solve #71 if ignoring records would automatically ignore their children as well (which we should do anyway imho)?

**Comment by pgrimsehl** [comment]
Yes I think that will work for this case too :)
