### ISSUE TITLE
Record references as hyperlinks

### ISSUE THREAD

**Issue by pgrimsehl** [npruehs/tome-editor#74]
In large projects with many references to other records, it would be great if all references can be Shift-Clicked to jump to the definition of this record. It would be sufficient if this feature works in the record fields table.
This also requires a navigation history, to move back to the previous record that initiated the jump. Perhaps this can be integrated in Issue #20, by undoing a navigation action.

**Comment by npruehs** [comment]
Nice idea. This will require some means of "deep-linking" first, which we need for a basic search functionality anyway to make sense (#37). Navigation history would be a seperate feature, though.

**Comment by npruehs** [comment]
Added in commit 3878631779ddfb6e11d463ad0e9c7a2c1f05dfe7.
