### ISSUE TITLE
Bugreport Enums

### ISSUE THREAD

**Issue by OgoxHammerschild** [npruehs/tome-editor#83]
Hi Nick!
[Ich](https://www.linkedin.com/in/daniel-bortfeld-31b956106) gucke mir grad Tome 0.5 an und versuche herauszufinden, ob ich sowas gebrauchen kann :D
Dabei sind mir zwei Bugs aufgefallen, die ich dir mal reporten wollte:
- Wenn man bei CustomTypes/NewEnum keinen TypeName angibt und OK drückt, wird das Enum ohne TypeName erstellt und man kann es nicht mehr bearbeiten oder anderweitig damit interagieren.
- Wenn man einen TypeName aber kein Member angibt, OK drückt und dann dieses Enum bearbeitet, wurde bereits ein leeres Member hinzugefügt. Das nächste Member landet dann auf der zweiten Stelle. (das Leere kann man aber löschen)

Jetzt guck ich mir erst mal weiter das Wiki an * *Blick zur Uhr -> 2:30am* * ...oder vielleicht auch morgen. Hast du das ganze Wiki dazu geschrieben? Good job, hat bestimmt ganz schön lange gedauert. Ich schau mal, ob mir das bei meinem Abschlussprojekt helfen kann. Wenn das hier so öffentlich ist, denke ich mal, dass ich das auch für sowas verwenden kann, oder?

Viele Grüße
Daniel

**Comment by npruehs** [comment]
Hey Daniel,

thanks for your bug reports, they'll be resolved later today!

Yep, the wiki was a lot of work, but I feel like it was worth it. If you're missing anything, open an issue and I'm gonna add it.

Tome is public and licensed under the very permissive MIT license, so it should work well for your project. What are we dealing with?

This is an international issue tracker, so I'd like to ask you to post any further issues and comment in English :)

Cheers!
Nick

**Comment by OgoxHammerschild** [comment]
Hi Nick,

alright, I'll stick to English then :)

I'm still thinking about what I should do for my final SAE-project, but right now I'm playing with the thought of making an Anno-style RTS with focus on economy and city building and lesser focus on fighting. I'll probably make it with UE4, but first I need to make a prototype.

If I use Tome and miss something, I'll let you know :+1: 

Cheers,
Daniel

**Comment by npruehs** [comment]
Sounds great!

Unreal features support for a handful of text-based serialization formats, including JSON and XML:

https://docs.unrealengine.com/latest/INT/API/Runtime/Json/Serialization/index.html
https://docs.unrealengine.com/latest/INT/API/Runtime/XmlParser/index.html

But as you possibly already know, the true power of Tome lies in the ability of supporting virtually any format.

You've already found the wiki. If you're missing anything else, take a look at the development roadmap - chances are it's already going to be added:

https://github.com/npruehs/tome-editor/milestones

You can also contribute by creating issues ...

https://github.com/npruehs/tome-editor#bugs--feature-requests

... or actual code:

https://github.com/npruehs/tome-editor#contributing

In any case, I'd love to see what you're doing. Keep me posted! :)

**Comment by npruehs** [comment]
Fixed in commit 0ecb25fc88baaef1d0180038161dd3a04a774b0a.

**Comment by OgoxHammerschild** [comment]
Hey! I moved my repo from bitbucket to github. Go [here](https://github.com/OgoxHammerschild/etos) to check it out, if you want. The idea I posted here earlier is the one i sticked with.

**Comment by npruehs** [comment]
Neat! Let me know if you need anything :)
