### ISSUE TITLE
Usage of <Path> element for export templates inconsistent / broken

### ISSUE THREAD

**Issue by pgrimsehl** [npruehs/tome-editor#84]
Since the appreciated change to move Record Export Templates, Field Definitions, Types etc.  to separate files, it is no longer possible to reference Record Export Templates that are not located in the project folder.

In Project version < 4 the export section of the project  was defined as

```
    <RecordExportTemplates>
        <Template Path="../shared" ExportLeafs="true">
            <Name>INI</Name>
            <FileExtension>.ini</FileExtension>
            <TypeMap/>
        </Template>
    </RecordExportTemplates>
```

with an added attribute _Path_ to specify the path where to look for the file.

In project version 4 this should be written as
```
    <RecordExportTemplates>
        <Path>../shared/INI</Path>
    </RecordExportTemplates>
```
Currently the value of the Path element is interpreted as **name** of the template, not as the path to the .texport file, as the name and the usage of all other Path elements in the project file suggests.
Additionally, the _Path_ attribute in the .texport file no longer makes sense.

**Comment by npruehs** [comment]
Will take a look at it this evening!

**Comment by npruehs** [comment]
Also, thanks for pointing out the inconsistency with respect to _name_ and _path_ fields.
