### ISSUE TITLE
Limit Record Export Template responsibility and extend functionality

### ISSUE THREAD

**Issue by pgrimsehl** [npruehs/tome-editor#85]
Ok, perhaps I'm a bit picky about this, but I think a Record Export Template should only manage HOW the data gets exported and not WHAT data gets exported. This is especially true for very generic export formats, such as CSV or INI. Therefore the following section 

```
<IgnoredRecords>
    <Id>...</Id>
</IgnoredRecords>
<IgnoredFields>
    <Id>...</Id>
</IgnoredFields>
```

should be moved to the project file, as well as all flags used to control export behaviour ( ExportLeafs etc. ), because all of these parameters are project specific and should not be part of the export template.

Of course my proposed and newly added feature #72 violates this rule, as it forces the usage of explicit field names, which again are project dependent.

To solve this, I suggest the introduction of Export Template Placeholders, which can be utilized to control the export behaviour as described below.

The .texport file will be extended by a Placeholder section
```
<Placeholders>
    <Placeholder Id="PlaceholderName" DisplayName="PlaceholderDisplayName">PlaceholderDefaultValue</Placeholder>
    . . .
</Placeholders>
```
This section could be displayed later in "Project Settings -> Export Configuration" (or something like that) for each export template that is used by the project. Here, the user can change the default values to whatever fits his current project. The overridden default values will be stored in the project file within the corresponding template section.

Export Template Placeholders are referenced in the export template files using a special escape sequence, for example `!PlaceholderName!`. (Escaping with ! is just an example)

Example 1: CSV export:

CSV.texport
```
<?xml version="1.0" encoding="UTF-8"?>
<Template>
    <Name>CSV</Name>
    <FileExtension>.csv</FileExtension>
    <TypeMap/>
    <Placeholders>
        <Placeholder Id="Separator" DisplayName="Separator">;</Placeholder>
        <Placeholder Id="HeaderRecordColumnName" DisplayName="HeaderRecordColumnName">Object</Placeholder>
    </Placeholders>
</Template>
```
CSV.texportf
`!HeaderRecordColumnName!$FIELD_NAMES:!Separator!$`

CSV.texportr
`$RECORD_ID$!Separator!$RECORD_FIELDS$`

CSV.texportvd
`!Separator!`

If the export target would require another separator, for example |, the user could simple change this in the project settings for CSV export, without the need to duplicate the complete file set, renaming it to "CSV using |" ( which would be an illegal filename anyway ) and manually changing all occurences of ; to |.
In this example I quietly introduced the new $FIELD_NAMES:_FieldNameSeparator_>$ placeholder syntax, which just prints a list of all fields in the project (omitting the IgnoredFields) using the supplied string after : as separator. This syntax is mandatory in my example, since explicitly enumerating the fields would require knowledge of the project, which I want to eliminate in the first place ;)
The user could also define how the first column containing the record names should be titled, for example "Unit".

Example 2: Tiled Object Types export:

Tiled Object Types.texport
```
<?xml version="1.0" encoding="UTF-8"?>
<Template>
    <Name>Tiled Object Types</Name>
    <FileExtension>.xml</FileExtension>
    <TypeMap/>
    <Placeholders>
        <Placeholder Id="ColorAttribute" DisplayName="Color Attribute">Color</Placeholder>
    </Placeholders>
</Template>
```

Tiled Object Types.texportr
```
 <objecttype name="$RECORD_ID$" color="$FIELD_VALUE:!ColorAttribute!$">
$RECORD_FIELDS$
 </objecttype>
```

This export format requires a color attribute for the objecttype element. Depending on the project, this color could be stored in a field named "Color", "ObjectColor" or "col_attr" and this name could be entered as new value for the ColorAttribute export template parameter.

What do you think of this?

**Comment by npruehs** [comment]
I think I understand your suggestion, but I'm wondering whether this actually adds anything that we weren't able to do before? Moving "IgnoredRecords" tags back to the project file would require you to have multiple project files again as shown in #71.

Also, I fail to see which benefit adding Placeholder has, except for your example 1. However, I feel like that example is highly unlikely in real world applications - I expect projects to have profoundly different export templates (such as one for exporting ProtoBuf schemas or C# class files and one for export YAML or JSON data files). 

The idea of introducing Placeholder in order to be able to share "very generic export formats" is noble, but I think that is highly unlikely to happen, too. After all, each project will define their own template file (which is the main motivation behind Tome!). I expect export templates to behave pretty similar to build scripts in this regard: Almost no project will ever re-use the exact same export template, but copy and slightly modify it instead.

**Comment by pgrimsehl** [comment]
On second thought maybe I was over generalizing the concept of record export templates I will evaluate this during the actual content generation process. Meanwhile this issue can be closed.

**Comment by npruehs** [comment]
Sure, I'm eager to see your results!
