### ISSUE TITLE
Loading project with version < 4 broken

### ISSUE THREAD

**Issue by pgrimsehl** [npruehs/tome-editor#86]
Since resolving #84 loading projects with version 3 or lower does not work anymore. The export template path generation does not include the template name. 
Additionally (after applying a local fix for that) saving v3 projects will create a .texport file without name and the Path element of the template in the project file is empty.

**Comment by npruehs** [comment]
Fixed a bug in deserializing older project files. For me, opening a v3 project file and saving it correctly creates the .texport files. If that's not the case for you after applying this fix, can you provide a repro?
