### ISSUE TITLE
Moving records between record sets

### ISSUE THREAD

**Issue by pgrimsehl** [npruehs/tome-editor#87]
A Tome project can reference / use multiple record set files, which is great when working with master / sub projects or simply to break down the overall data into smaller chunks.

By default, new records are added to the first record set in the list of project records. When re-parenting a record, only the parent id will be change, but it won't be physically moved to the record set of the parent. In turn, this will result in an inconsistent .tdata file, where the referenced parent is not present.

The record ( and all of it's children) should be moved to the parent record set.

**Comment by npruehs** [comment]
Yeah, specifying the actual record set of a record had already been implemented in 0.1, but wasn't ported to the Qt version. Back in 0.1, you could specify the record set in the "Edit Record" window (where you can change the name and add fields).

I'd put it back there, if you don't mind?

Also, do you really want to automatically move the records between files by re-parenting them? That seems to contradict the idea of your master-sub-project setup I had in mind, maybe you can clarify in #68 for me :)

**Comment by pgrimsehl** [comment]
Yeah you're right here, adding childs to a root record from a master project must not add these reords to the master record set. I was mainly concerned about the integrity of the .tdata file, which should contain all records that a referenced by records contained in the set. But actually your master/sub project use case proves that this is the common case. The user just has to make sure that all required .tdata files are included in the sub project.
Showing and being able to change the record set name in the 'Edit Record' window will help to manage record affinity to record sets.

**Comment by npruehs** [comment]
Added in commit d711f2ae4023bcfa12dd1a1cb19dc9cc31a21053.
