### ISSUE TITLE
Tome crashes when adding new fields with facets

### ISSUE THREAD

**Issue by pgrimsehl** [npruehs/tome-editor#89]
There are several issues with the new facets:
1. Creating a new field will not show any facet widgets in the field dialog, regardless of selected type, If any field definition unsing facets was edited before, facet widgets from this field definition will be shown instead.
2. When editing an existing field, facet widgets will not change when changing the field type.
3. Creating a new field using a type with facets (e.g. Integer) will crash the application when confirming the dialog (FieldDefinitionWindow::getFieldFacets() in fielddefinitionwindow.cpp, line 103) because no widgets were created as stated in 1.

Are facets meant to be defined for field definitions or for instances of fields or both?

**Comment by pgrimsehl** [comment]
I found a fix for this problem, commited [here](https://github.com/pgrimsehl/tome-editor/commit/fc50d34dea806d742395482dcfbcbc4393775587).

**Comment by npruehs** [comment]
@pgrimsehl Thanks for the heads up! Will take a look at it later today!

**Comment by npruehs** [comment]
Yep, that's exactly the way I'd have done it :) Thanks for the fix!
