### ISSUE TITLE
$FIELD_COMPONENT$ Value

### ISSUE THREAD

**Issue by WildPyromancer** [npruehs/tome-editor#91]
For some architectures, it would be extremely helpful to know what Component a field is associated with when generating the data. Is it possible that this field could be exposed?

**Comment by npruehs** [comment]
Sure, no problem. Added in commit 9a1ece333ce1ad284e894e04e769ddbf970f076b. You can now use $FIELD_COMPONENT$ in your field value export templates (.texportv). Tell me if that helps!

**Comment by WildPyromancer** [comment]
Excellent! Any idea when it's going to be in a release?

**Comment by WildPyromancer** [comment]
Also, it may be useful to expose the rest of the data that is displayed in the tool to the exporter templates. It would allow for that much more fine-grained control over the export process.

**Comment by npruehs** [comment]
@WildPyromancer You can always see the release an issue is assigned to to the right, just below the Milestone label. Clicking on the milestone of this issue will tell you that it's scheduled for November 15. You're a little unlucky - we're issuing monthly releases, and the last release was, well ... today ;)

If you're in dire need, I can provide an intermediate build. Also, you can always grab [Qt](https://www.qt.io/) and open the project file yourself. It should compile right away, no annoying additional setup required.

I've added placeholders for display names and descriptions as well in commit 8e05e74cb3e46d89a210dd691e2970430552120f. Please tell me if you need anything else!
