### ISSUE TITLE
Bug: Crash when component name mismatch encountered.

### ISSUE THREAD

**Issue by ForgeMistress** [npruehs/tome-editor#94]
I had to manually edit some files to change a field name as well as some component names and found that when a that a encounters a field/component pair that isn't present in any tfields files, it will crash.

**Comment by WildPyromancer** [comment]
That when a tdata*

I got autocorrected.

**Comment by npruehs** [comment]
Why did you have to edit some data manually? Did you need to work around something?

What do you mean by "encounters"? When does the application crash?

When loading the project? Saving it? Selecting a record? Opening the field definition window? Exporting data?

**Comment by WildPyromancer** [comment]
The crash occurs on saving, and by "encounters", I mean that I believe it occurs when it's traversing the XML tree while expecting to find one element with a certain name but then encountering another.

And in all honesty, I sometimes manually edit the tproj files when I get lazy (the UI could be a bit more elegant when it comes to components and fields, but that is a writeup for another day).

**Comment by npruehs** [comment]
I can't seem to reproduce the issue... I've deleted both arbitrary field and component data, opened and saved the project - no crash. Could you attach a repro project?
