### ISSUE TITLE
Feature $DATE$, $APP_VERSION$ as export placeholders

### ISSUE THREAD

**Issue by pgrimsehl** [npruehs/tome-editor#97]
The user should be able to generate time/date and version information in the exported files.

**Comment by npruehs** [comment]
Any specifics? Which date/time format? Which kind of version information do you expect? Tome application version? Data version?

**Comment by pgrimsehl** [comment]
$DATE$ / $TIME$: Date/time format should use the project locale
$APP_VERSION$: application version of Tome

Example:

```
// config.ini
// Exported using Tome $APP_VERSION$
// Last change: $DATE$ $TIME$
```
should produce
```
// config.ini
// Exported using Tome Version 0.6 (Hydra)
// Last change: 10/20/2016 12:43
```
Of course it's debatable if the time should include seconds or can be configured to use 12hours.

**Comment by npruehs** [comment]
Alright, should be easy to do :)

**Comment by npruehs** [comment]
Added placeholders $APP_VERSION$, $APP_VERSION_NAME$ and $EXPORT_TIME$ in commit 9ee8514817689d0b79e9a48e26202a7a8de594ab.
