### ISSUE TITLE
Feature: Facets for custom types

### ISSUE THREAD

**Issue by pgrimsehl** [npruehs/tome-editor#98]
The user should be able to assign facets to custom types:

List: facet for contained type
Map: facet for key type and facet for value type

**Comment by npruehs** [comment]
Can you give an example, just to make sure we're talking about the same thing? Do you mean something like: "I want to make a list which contains only numbers between 1 and 10"?

**Comment by pgrimsehl** [comment]
Example:

I'm defining a production chain and creating Product records. A product can use other products as input for production, using a field "Input" of type "ProductInputType"
ProductInputType is defined as a map type (Reference -> Real), where the Reference is a product record and the Real is the amount used of that product.
The user should only be able to select Product records as keys when adding elements to the field.

**Comment by npruehs** [comment]
Thank you, understood. I can see why this makes sense.

**Comment by npruehs** [comment]
@pgrimsehl I'm seriously considering moving facets to custom types themselves. I'd introduce the possibility of defining custom types based on existing types, much like in XML Schema.

Example:

You can define your own custom type "PositiveInteger" based on Integer with the facet MinimumValue = 1.

Upsides:

* You only need to define facets once if you need them for multiple fields.
* Facets are automatically applied wherever you specify a field value (such as default values, field values, list or map items).

Downside:

* Whenever you need a facet, you'd have to define a custom type first, which might become tedious if you have many slightly different facets.

What do you think?

**Comment by pgrimsehl** [comment]
I like the idea of making facets a part of the type definition itself.

Am 26.10.2016 09:09 schrieb "Nick Pruehs" <notifications@github.com>:

**Comment by npruehs** [comment]
Added in commit 0562a30e6a035bcb18a0d203eaafceb6262bb1be. You'll have to define your facets again, as it's hard to find an automatic mapping between field facets and type facets.
