### ISSUE TITLE
Feature: Project status

### ISSUE THREAD

**Issue by pgrimsehl** [npruehs/tome-editor#99]
The user should get a clear (visual) indication if any changes were made to the project after opening it.
When closing a project / exiting the application and changes were made to the current project, the user should be prompted how to handle the changes ( save, discard, abort ).

**Comment by npruehs** [comment]
This closely tied to #20 Undo & Redo.

**Comment by npruehs** [comment]
Added in commit e25d6739351741243c9ab92a8d0ae2126010694c.
